### ISSUE TITLE
OS Version ??

### ISSUE THREAD

**Issue by FrancoisDevemy5** [nielsbasjes/yauaa#594]
Sometimes between version 5.18 and 6.12 when the OS version was unknown it stopped being reported as the string "??" and is now just empty.

But not for this agent.

```

- test:
    input:
      User-Agent  : 'Mozilla/5.0 (Windows NT; Windows NT 10.0; fr-FR) WindowsPowerShell/5.1.19041.1237'
    expected:
      DeviceClass  : 'Desktop'
      DeviceName  : 'Desktop'
      DeviceBrand  : 'Unknown'
      DeviceCpuBits  : '32'
      OperatingSystemClass  : 'Desktop'
      OperatingSystemName  : 'Windows NT'
      OperatingSystemVersion  : '??'
      OperatingSystemVersionMajor  : '??'
      OperatingSystemNameVersion  : 'Windows NT ??'
      OperatingSystemNameVersionMajor  : 'Windows NT ??'
      LayoutEngineClass  : 'Browser'
      LayoutEngineName  : 'Mozilla'
      LayoutEngineVersion  : '5.0'
      LayoutEngineVersionMajor  : '5'
      LayoutEngineNameVersion  : 'Mozilla 5.0'
      LayoutEngineNameVersionMajor  : 'Mozilla 5'
      AgentClass  : 'Browser'
      AgentName  : 'WindowsPowerShell'
      AgentVersion  : '5.1.19041.1237'
      AgentVersionMajor  : '5'
      AgentNameVersion  : 'WindowsPowerShell 5.1.19041.1237'
      AgentNameVersionMajor  : 'WindowsPowerShell 5'
      AgentLanguage  : 'French (France)'
      AgentLanguageCode  : 'fr-fr'

```

**Comment by nielsbasjes** [comment]
Do you have an example of the other situation?

**Comment by FrancoisDevemy5** [comment]
Hello. What do you mean by the other situation?

**Comment by FrancoisDevemy5** [comment]
Here is an example of an agent that used to have `??` as OS version but have an empty string now : 
`Jakarta Commons-HttpClient/3.1`

**Comment by nielsbasjes** [comment]
The Windows 10 example you posted before should report Windows 10, that needs a fix.

This what I get with 7.1.0.
I see a value for the OS and the OS version shows "??".
I do not yet understand the problem in this example



- test:
    input:
      User-Agent                           : 'Jakarta Commons-HttpClient/3.1'
    expected:
      DeviceClass                          : 'Robot'
      DeviceName                           : 'Jakarta Commons-HttpClient'
      DeviceBrand                          : 'Jakarta Commons-HttpClient'
      OperatingSystemClass                 : 'Cloud'
      OperatingSystemName                  : 'Cloud'
      OperatingSystemVersion               : '??'
      OperatingSystemVersionMajor          : '??'
      OperatingSystemNameVersion           : 'Cloud ??'
      OperatingSystemNameVersionMajor      : 'Cloud ??'
      LayoutEngineClass                    : 'Robot'
      LayoutEngineName                     : 'Jakarta Commons-HttpClient'
      LayoutEngineVersion                  : '3.1'
      LayoutEngineVersionMajor             : '3'
      LayoutEngineNameVersion              : 'Jakarta Commons-HttpClient 3.1'
      LayoutEngineNameVersionMajor         : 'Jakarta Commons-HttpClient 3'
      AgentClass                           : 'Robot'
      AgentName                            : 'Jakarta Commons-HttpClient'
      AgentVersion                         : '3.1'
      AgentVersionMajor                    : '3'
      AgentNameVersion                     : 'Jakarta Commons-HttpClient 3.1'
      AgentNameVersionMajor                : 'Jakarta Commons-HttpClient 3'

**Comment by nielsbasjes** [comment]
I have fixed the 'Windows NT ??' which now shows 'Windows 10.0'.
The other points you make about the version being either '??' or absent is something that has changed about a year ago.

I still do not understand the issue you are trying to report.
I read that the OS version is empty instead of being '??', but when try it in the latest version I get '??'. Sam with the other one you reported (https://github.com/nielsbasjes/yauaa/issues/595) here also I get a clean '??' which is correct.

**Comment by nielsbasjes** [comment]
The Windows 10 situation has been fixed
https://github.com/nielsbasjes/yauaa/blob/main/analyzer/src/main/resources/UserAgents/Windows.yaml#L669

Regarding the other situation.
I do not understand what is wrong here so I'm closing this issue.
Please reopen if you have more information.

**Comment by FrancoisDevemy5** [comment]
I described the problem here: https://github.com/nielsbasjes/yauaa/issues/595#issuecomment-1150212921
(of course here the relevant field is `OPERATING_SYSTEM_VERSION_MAJOR` instead of `AGENT_VERSION_MAJOR`).

**Comment by rupebac** [comment]
The following UserAgent is still unable to parse the OS version (??):

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.63 Safari/537.36 

Is this an unknown problem?

**Comment by nielsbasjes** [comment]
> The following UserAgent is still unable to parse the OS version (??):
> 
> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.63 Safari/537.36 
> 
> Is this an unknown problem?

This should answer your question:

https://yauaa.basjes.nl/developer/reportingissues/#these-are-not-bugs
